// LOCAL
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';

// API
export const SEARCH_PRODUCTS     = 'SEARCH_PRODUCTS';
export const RECEIVE_PRODUCTS    = 'RECEIVE_PRODUCTS';
export const GET_PRODUCT         = 'GET_PRODUCT';
export const UPDATE_ALL_PRODUCTS = 'UPDATE_ALL_PRODUCTS';