// LOCAL
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';

export const SET_FILTER = 'SET_FILTER';
export const SET_SORT   = 'SET_SORT';

// API
export const PRODUCT_SEARCH_REQUEST = 'PRODUCT_SEARCH_REQUEST'
export const PRODUCT_SEARCH_SUCCESS = 'PRODUCT_SEARCH_SUCCESS'
export const PRODUCT_SEARCH_FAILURE = 'PRODUCT_SEARCH_FAILURE'

export const SEARCH_PRODUCTS     = 'SEARCH_PRODUCTS';

export const RECEIVE_PRODUCTS    = 'RECEIVE_PRODUCTS';
export const GET_PRODUCT         = 'GET_PRODUCT';
export const UPDATE_ALL_PRODUCTS = 'UPDATE_ALL_PRODUCTS';